[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "capmodels"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Juan Luis Cano Rodríguez", email = "hello@juanlu.space" }
]
requires-python = ">=3.10"
dependencies = [
    "pydantic-xml>=2.13.1",
]
